"""
06_evaluate.py — Final Evaluation.

Implements two evaluation stages:

    run_pt_experiment():
        Loads the gold qrels (generated by 04_ground_truth.py) and runs pt.Experiment
        comparing five retrieval pipelines:
            P0: BM25
            P1: BM25 + RM3
            P2: BM25 + Social features
            P3: BM25 + Graph features
            P4: BM25 + All features (Full LTR)
        Saves results to results/experiment_results.csv.

    run_ablation_study():
        Compares each feature group independently to quantify their
        individual contribution. Exports results/ablation_results.csv.

Inputs:
    data/processed/queries/test_queries.pkl
    data/processed/qrels/test_gold.csv
    data/processed/all_features.pkl
    models/ltr_model.pkl
    models/ltr_scaler.pkl
    index/

Outputs:
    results/experiment_results.csv
    results/ablation_results.csv

Usage:
    python src/06_evaluate.py experiment
    python src/06_evaluate.py ablation
"""

import os
import sys
from pathlib import Path

import numpy as np
import pandas as pd

sys.path.insert(0, str(Path(__file__).parent.parent))
from src.utils import load_pkl, save_pkl, get_logger, PROCESSED_DIR

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------

TEST_QUERIES_PATH = PROCESSED_DIR / "queries" / "test_queries.pkl"
TEST_GOLD_PATH    = PROCESSED_DIR / "qrels"   / "test_gold.csv"
ALL_FEATURES_PATH = PROCESSED_DIR / "all_features.pkl"

BASE_DIR          = Path(__file__).resolve().parent.parent
MODELS_DIR        = BASE_DIR / "models"
MODEL_PATH        = MODELS_DIR / "ltr_model.pkl"
SCALER_PATH       = MODELS_DIR / "ltr_scaler.pkl"
INDEX_DIR         = BASE_DIR / "index"

RESULTS_DIR            = BASE_DIR / "results"
EXPERIMENT_RESULTS     = RESULTS_DIR / "experiment_results.csv"
ABLATION_RESULTS       = RESULTS_DIR / "ablation_results.csv"

# Feature column groups for ablation
SOCIAL_COLS  = ["F_SOC_SCORE",  "F_SOC_UPVOTE", "F_SOC_ENGAGE"]
GRAPH_COLS   = ["F_GRAPH_DEG",  "F_GRAPH_BET",  "F_GRAPH_COMM"]
CONTENT_COLS = ["F_CONT_SENT",  "F_CONT_NER",   "F_CONT_MONEY"]
ALL_FEAT_COLS = SOCIAL_COLS + GRAPH_COLS + CONTENT_COLS

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

log = get_logger("evaluate")


# ---------------------------------------------------------------------------
# Java / PyTerrier initialization
# ---------------------------------------------------------------------------

def _init_pt() -> None:
    """Initialize PyTerrier."""
    import pyterrier as pt
    if not pt.java.started():
        pt.java.init()


def load_gold_qrels(path: Path = TEST_GOLD_PATH) -> pd.DataFrame:
    """
    Load gold qrels from CSV.

    Expected CSV columns: qid, docno, label (0 or 1).

    Args:
        path: Path to the annotated CSV file.

    Returns:
        Gold qrels DataFrame with columns [qid, docno, label].

    Raises:
        FileNotFoundError: If the annotation file has not been created yet.
    """
    if not path.exists():
        raise FileNotFoundError(
            f"Gold qrels not found at '{path}'.\n"
            "Run src/04_ground_truth.py first to generate test_gold.csv"
        )
    qrels = pd.read_csv(path)
    qrels["qid"] = qrels["qid"].astype(str)
    qrels["label"] = pd.to_numeric(qrels["label"], errors="coerce").fillna(0).astype(int)
    log.info("Gold qrels loaded — %d pairs  positive=%d",
             len(qrels), qrels["label"].sum())
    return qrels


# ===========================================================================
# Run pt.Experiment on test set
# ===========================================================================

def _build_feature_reranker(
    doc_features: pd.DataFrame,
    feature_cols: list[str],
    model,
    scaler,
    alpha: float = 0.3,
) -> object:
    """
    Build a PyTerrier Transformer that re-ranks using a subset of features.

    Args:
        doc_features: Full feature matrix indexed by docno.
        feature_cols: Subset of feature columns to use.
        model:        Trained LogisticRegression.
        scaler:       Fitted StandardScaler (fitted on all features).
        alpha:        BM25 weight in blended score.

    Returns:
        pt.apply.generic Transformer compatible with pt.Experiment.
    """
    import pyterrier as pt
    from src.utils import min_max_normalize  # type: ignore

    # Determine which scaler columns correspond to our feature_cols
    # The scaler was fitted on ["bm25_norm"] + ALL_FEAT_COLS
    all_cols_in_scaler = ["bm25_norm"] + ALL_FEAT_COLS
    col_indices = [0] + [all_cols_in_scaler.index(c) for c in feature_cols]

    def _rerank_fn(results: pd.DataFrame) -> pd.DataFrame:
        results = results.copy()
        # Normalize BM25 per query
        results["bm25_norm"] = (
            results.groupby("qid")["score"]
            .transform(lambda s: min_max_normalize(s))
            .fillna(0.0)
        )
        # Attach selected features
        feat_df = doc_features[feature_cols].reindex(results["docno"].values).fillna(0.0)
        X_full = pd.concat(
            [results[["bm25_norm"]].reset_index(drop=True),
             feat_df.reset_index(drop=True)],
            axis=1,
        ).values.astype(float)

        # Scale using only the relevant column indices
        X_scaled = scaler.transform(
            pd.DataFrame(
                [[0.0] * len(all_cols_in_scaler)] * len(X_full),
                columns=all_cols_in_scaler,
            ).assign(**{
                "bm25_norm": X_full[:, 0],
                **{c: X_full[:, i + 1] for i, c in enumerate(feature_cols)},
            }).values
        )

        p_rel = model.predict_proba(X_scaled)[:, 1]
        results["score"] = alpha * results["bm25_norm"] + (1 - alpha) * p_rel
        return results.sort_values(["qid", "score"], ascending=[True, False])

    return pt.apply.generic(_rerank_fn)


def run_pt_experiment() -> pd.DataFrame:
    """
    Run pt.Experiment comparing five retrieval pipelines on the gold test set.

    Pipelines evaluated:
        P0: BM25                — lexical baseline
        P1: BM25 + RM3          — query expansion baseline
        P2: BM25 + Social       — social trust features only
        P3: BM25 + Graph        — author authority features only
        P4: BM25 + Full LTR     — all four dimensions

    Metrics: nDCG@10, MAP@1000, P@5, RR@10.

    Returns:
        pt.Experiment results DataFrame.
    """
    _init_pt()
    import pyterrier as pt
    import importlib
    indexer_mod = importlib.import_module("src.02_indexer")
    load_index = indexer_mod.load_index
    get_bm25_retriever = indexer_mod.get_bm25_retriever

    test_queries  = load_pkl(TEST_QUERIES_PATH)
    gold_qrels    = load_gold_qrels()
    doc_features  = load_pkl(ALL_FEATURES_PATH)
    model         = load_pkl(MODEL_PATH)
    scaler        = load_pkl(SCALER_PATH)

    index = load_index(INDEX_DIR)
    bm25  = get_bm25_retriever(index, num_results=1000)

    # P0: BM25 baseline
    P0 = bm25

    # P1: BM25 + RM3 query expansion
    P1 = bm25 >> pt.rewrite.RM3(index, fb_terms=10, fb_docs=3) >> bm25

    # P2: BM25 + Social features only
    P2 = bm25 >> _build_feature_reranker(doc_features, SOCIAL_COLS,  model, scaler)

    # P3: BM25 + Graph features only
    P3 = bm25 >> _build_feature_reranker(doc_features, GRAPH_COLS,   model, scaler)

    # P4: BM25 + Full LTR (all features)
    P4 = bm25 >> _build_feature_reranker(doc_features, ALL_FEAT_COLS, model, scaler)

    pipelines = [P0, P1, P2, P3, P4]
    names     = ["BM25", "BM25+RM3", "BM25+Social", "BM25+Graph", "BM25+Full"]

    log.info("Running pt.Experiment with %d pipelines...", len(pipelines))
    experiment = pt.Experiment(
        pipelines,
        test_queries,
        gold_qrels,
        eval_metrics=["ndcg_cut_10", "map", "P_5", "recip_rank"],
        names=names,
        baseline=0,
        correction="b",        # Bonferroni correction for multiple comparisons
        verbose=True,
    )

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    experiment.to_csv(EXPERIMENT_RESULTS, index=False)
    log.info("Experiment results saved → %s", EXPERIMENT_RESULTS)
    log.info("\n%s", experiment.to_string())
    return experiment


# ===========================================================================
# Ablation study
# ===========================================================================

def run_ablation_study() -> pd.DataFrame:
    """
    Ablation study: measure the marginal contribution of each feature group.

    Compares five configurations:
        1. BM25 only (no features)
        2. BM25 + Social features
        3. BM25 + Graph features
        4. BM25 + Content features
        5. BM25 + All features (full model)

    Results are saved to results/ablation_results.csv.

    Returns:
        Ablation results DataFrame.
    """
    _init_pt()
    import pyterrier as pt
    import importlib
    indexer_mod = importlib.import_module("src.02_indexer")
    load_index = indexer_mod.load_index
    get_bm25_retriever = indexer_mod.get_bm25_retriever

    test_queries = load_pkl(TEST_QUERIES_PATH)
    gold_qrels   = load_gold_qrels()
    doc_features = load_pkl(ALL_FEATURES_PATH)
    model        = load_pkl(MODEL_PATH)
    scaler       = load_pkl(SCALER_PATH)

    index = load_index(INDEX_DIR)
    bm25  = get_bm25_retriever(index, num_results=1000)

    pipelines = [
        bm25,
        bm25 >> _build_feature_reranker(doc_features, SOCIAL_COLS,   model, scaler),
        bm25 >> _build_feature_reranker(doc_features, GRAPH_COLS,    model, scaler),
        bm25 >> _build_feature_reranker(doc_features, CONTENT_COLS,  model, scaler),
        bm25 >> _build_feature_reranker(doc_features, ALL_FEAT_COLS, model, scaler),
    ]
    names = [
        "BM25 only",
        "BM25 + Social",
        "BM25 + Graph",
        "BM25 + Content",
        "BM25 + Full LTR",
    ]

    log.info("Running ablation study (%d configurations)...", len(pipelines))
    ablation = pt.Experiment(
        pipelines,
        test_queries,
        gold_qrels,
        eval_metrics=["ndcg_cut_10", "map", "P_5"],
        names=names,
        baseline=0,
        verbose=True,
    )

    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    ablation.to_csv(ABLATION_RESULTS, index=False)
    log.info("Ablation results saved → %s", ABLATION_RESULTS)
    log.info("\n%s", ablation.to_string())
    return ablation


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    if len(sys.argv) > 1:
        cmd = sys.argv[1].lower()
        if cmd == "experiment":
            run_pt_experiment()
        elif cmd == "ablation":
            run_ablation_study()
        else:
            print("Unknown command. Use: experiment, or ablation")
    else:
        log.info("=== Smoke test: evaluate.py logic (no index/gold qrels needed) ===")

        import tempfile

        # Simulate gold qrels load from CSV
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".csv", delete=False, encoding="utf-8"
        ) as f:
            f.write("qid,docno,label\n")
            f.write("q1,d0,1\nq1,d1,1\nq1,d2,0\n")
            f.write("q2,d3,1\nq2,d4,0\nq2,d5,0\n")
            tmp_path = Path(f.name)

        qrels = load_gold_qrels(tmp_path)
        assert len(qrels) == 6,       f"Expected 6 rows, got {len(qrels)}"
        assert qrels["label"].sum() == 3, "Expected 3 positive labels"
        log.info("load_gold_qrels ✓  rows=%d  positives=%d",
                 len(qrels), qrels["label"].sum())

        tmp_path.unlink(missing_ok=True)

        log.info("=== All smoke tests passed ===")
        log.info("")
        log.info("Full evaluation workflow:")
        log.info("  1. python src/06_evaluate.py experiment")
        log.info("  2. python src/06_evaluate.py ablation")
